Repository JaManChu/backend, pull requests merged in 2024-10, with the labels that each got.

#21 [fix] OAuth2 (카카오) 테스트 코드 수정
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/LoginFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/auth/SignupDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/auth/UserDetailsDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/UserService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/auth/jwt/LoginFilterTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: fix

#23 [feat] Swagger Docs 추가
  jamanchu/build.gradle
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/SwaggerConfig.java
Labels: enhancement

#26 [feat] Data Scraping 기능 구현
  jamanchu/build.gradle
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/TenThousandRecipeController.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/TenThousandRecipeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/crawling/ScrapResult.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/CookingTimeType.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/LevelType.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/TenThousandRecipeRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/scraper/ScrapTenThousandRecipe.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/ScrapTenThousandRecipeService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/ScrapTenThousandRecipeServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/entity/TenThousandRecipeEntityTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/ScrapTenThousandRecipeServiceImplTest.java
Labels: enhancement

#27 [feat] docker setting
  .gitignore
  docker-compose.yml
  jamanchu/.gitignore
  jamanchu/Dockerfile
  jamanchu/src/main/resources/application-dev.yml
  jamanchu/src/main/resources/application-prod.yml
  jamanchu/src/main/resources/application.yml
Labels: enhancement

#29 [fix] git 충돌 클래스 수정
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtUtil.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/LoginFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/test/java/com/recipe/jamanchu/auth/jwt/LoginFilterTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandlerTest.java
Labels: fix

#31 [fix] OAuth2 로그인 성공시 리다이렉트 로직 수정 및 로그 추가
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/CustomOauth2UserService.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
Labels: fix

#36 [feat] 댓글 관련 API 작성
  jamanchu/src/main/java/com/recipe/jamanchu/controller/CommentsController.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/CommentEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/ExceptionStatus.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/RecipeNotFoundException.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/UnmatchedUserException.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/CommentRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/CommentsService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/CommentsServiceImpl.java
  jamanchu/src/main/resources/application-dev.yml
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/CommentsServiceImplTest.java
Labels: enhancement

#35 [feat] 회원정보 수정 기능 구현
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtUtil.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/ExceptionStatus.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/SocialAccountException.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/auth/UserUpdateDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/UserRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/scraper/ScrapTenThousandRecipe.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/UserService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: enhancement

#38 [refactor] 회원 정보 수정 및 중복 코드 제거
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/UserEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/CommentsServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/component/UserAccessHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/CommentsServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: refactor

#42 [feat] Jacoco Test Coverage 도입
  jamanchu/build.gradle
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/CommentsServiceImplTest.java
Labels: enhancement

#41 [feat] 데이터 분산 저장 기능 구현
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/DataSaveController.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/ScrapTenThousandRecipeController.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/IngredientEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/ManualEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/RecipeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/TenThousandRecipeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/crawling/ScrapResult.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/RecipeProvider.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/TenThousandRecipeRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/scraper/ScrapTenThousandRecipe.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/RecipeDivideService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeDivideServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/ScrapTenThousandRecipeServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/entity/IngredientEntityTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/entity/RecipeEntityTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/entity/ScrapedRecipeEntityTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/entity/TenThousandRecipeEntityTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeDivideServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/ScrapTenThousandRecipeServiceImplTest.java
Labels: enhancement

#47 [refactor] WebMvcConfig 클래스 추가 및 UserController, ResultResponse
  jamanchu/src/main/java/com/recipe/jamanchu/config/WebMvcConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/ResultResponse.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/UserRepository.java
Labels: refactor

#49 [fix] 권한이 필요없는 경로명 수정
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
Labels: fix

#52 [feat] 스크랩 데이터 스케쥴링 구현
  jamanchu/src/main/java/com/recipe/jamanchu/JamanchuApplication.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/ScrapTenThousandRecipeController.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/TenThousandRecipeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/crawling/ScrapResult.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/TenThousandRecipeRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/scraper/ScrapTenThousandRecipe.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/ScrapTenThousandRecipeService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeDivideServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/ScrapTenThousandRecipeServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/util/LastRecipeIdUtil.java
  jamanchu/src/test/java/com/recipe/jamanchu/entity/TenThousandRecipeEntityTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/scraper/ScrapTenThousandRecipeTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeDivideServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/ScrapTenThousandRecipeServiceImplTest.java
Labels: enhancement

#54 [feat] 회원정보 조회 기능 구현
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/auth/UserInfoDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/UserService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: fix

#57 [refactor] Bussiness test code
  jamanchu/build.gradle
  jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/NotifyServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/CommentsServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/NotifyServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: Test

#59 [refactor] Exception And Valid Annotation
  jamanchu/src/main/java/com/recipe/jamanchu/controller/CommentsController.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/ExceptionStatus.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/GlobalExceptionHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/auth/DeleteUserDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/auth/EmailCheckDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/auth/SignupDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/auth/UserUpdateDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/comments/CommentsDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/comments/CommentsDeleteDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/comments/CommentsUpdateDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesDeleteDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesSearchDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesUpdateDTO.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/CommentsServiceImplTest.java
Labels: refactor

#61 [refactor] OAuth2SuccessHandler redirect URI 경로 변경 및 로그 위치 변경
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/WebMvcConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
Labels: refactor

#65 [fix] HttpMethod.OPTIONS 요청 권한 부여
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
Labels: fix

#68 [feat] 레시피 관련 API 작성
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/DataSaveController.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/RecipeController.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/RecipeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesDeleteDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesSearchDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesUpdateDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/ingredients/Ingredients.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/recipes/RecipesManual.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/recipes/RecipesManuals.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/recipes/RecipesSummary.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/IngredientRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/ManualRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/RecipeRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/RecipeService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesDTOTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesUpdateDTOTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeServiceImplTest.java
Labels: enhancement

#70 [feat] 레시피 스케쥴링 관련 수정
  jamanchu/src/main/java/com/recipe/jamanchu/entity/RecipeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/RecipeRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/scraper/ScrapTenThousandRecipe.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeDivideServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/util/LastRecipeIdUtil.java
  jamanchu/src/test/java/com/recipe/jamanchu/scraper/ScrapTenThousandRecipeTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeDivideServiceImplTest.java
Labels: enhancement

#72 [refactor] Login 로직 리팩토링
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/LoginFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/service/CustomUserDetailService.java
  jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/SwaggerConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/AuthController.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/ExceptionStatus.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/DuplicatedEmailException.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/MissingEmailException.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/auth/LoginDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/AuthService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/UserService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/AuthServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/auth/jwt/LoginFilterTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/auth/service/CustomUserDetailServiceTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/component/UserAccessHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/AuthServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: refactor

#75 [refactor] 레시피 관련 API들 문서에 맞게 변수명 수정
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesSearchDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesUpdateDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/comments/Comment.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/recipes/RecipesInfo.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/recipes/RecipesSummary.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/validator/AtLeastOneNotEmptyValidator.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/CommentsServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeServiceImplTest.java
Labels: refactor

#76 [refactor] Jwt 토큰 헤더 명 변경 및 로그인 성공시 닉네임 추가 반환
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/SwaggerConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/WebMvcConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/UserService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/CommentsServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/CommentsServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: refactor

#78 Fix/#77/o auth login
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/CustomOauth2UserService.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2FailureHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/ExceptionStatus.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/AccessTokenRetrievalException.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/UserInfoRetrievalException.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/UserService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2FailureHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/auth/oauth2/handler/OAuth2SuccessHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: fix

#82 [feat] 레시피 리스트, 상세 정보에 rating 추가
  jamanchu/src/main/java/com/recipe/jamanchu/entity/RecipeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/RecipeRatingEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/recipes/RecipesInfo.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/recipes/RecipesSummary.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/RecipeRatingRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeServiceImplTest.java
Labels: enhancement

#80 [fix] Swagger Config 수정 - localhost Server Item 추가
  jamanchu/src/main/java/com/recipe/jamanchu/config/SwaggerConfig.java
Labels: fix

#89 [refactor] Alarm 구조 변경
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/notify/NotifyController.java
  jamanchu/src/main/java/com/recipe/jamanchu/notify/Subscribers.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/NotifyService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/CommentsServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/NotifyServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/NotifyServiceImplTest.java
Labels: refactor

#90 [refactor] Options 요청 JwtFilter 검증 제외 및 토큰 헤더 명 Enum값 사용
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/SwaggerConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/WebMvcConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/TokenType.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/CommentsServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/CommentsServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: fix, refactor

#91 [feature] 레시피 상세조회 시 쿠팡링크, 댓글 부분 삭제
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/ingredients/IngredientCoupang.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/recipes/RecipesInfo.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeServiceImplTest.java
Labels: enhancement

#93 [fix] 레시피 API permit 수정
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
Labels: fix

#100 [feat] 닉네임 중복 검사 로직 구현
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/AuthController.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/ExceptionStatus.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/DuplicatedNicknameException.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/MissingNicknameException.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/AuthService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/AuthServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/component/UserAccessHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/AuthServiceImplTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: enhancement, refactor

#95 [feat] 내가 스크랩한 레시피 & 내가 작성한 레시피 조회 API 구현
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/mypage/MyRecipeInfo.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/mypage/MyRecipes.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/mypage/MyScrapedRecipes.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/mypage/PageResponse.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/RecipeRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/UserService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: enhancement

#102 [feat] docker-compose.yml npm 설정 추가
  docker-compose.yml
Labels: enhancement

#104 [fix] comment DTO와 CommentEntity Fetch Type 변경
  jamanchu/src/main/java/com/recipe/jamanchu/entity/CommentEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/comments/CommentsDTO.java
Labels: fix

#108 [fix] CommentsUpdateDTO에서 Inclusive 제외
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/comments/CommentsUpdateDTO.java
Labels: fix

#109 [feat] 레시피 등록 및 수정시에 MappingTable에도 내용 저장되도록 구현
  jamanchu/src/main/java/com/recipe/jamanchu/repository/IngredientRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/RecipeIngredientMappingRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeServiceImplTest.java
Labels: enhancement

#111 [fix] 재료명 사이에 빈칸이 있을 경우 처리 추가
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeDivideServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeDivideServiceImplTest.java
Labels: fix

#112 [feat] refresh 토큰 재발급 로직 구현
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtUtil.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/SecurityConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/AuthController.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/ExceptionStatus.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/CookieNotFoundException.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/RefreshTokenExpiredException.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/AuthService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/AuthServiceImpl.java
  jamanchu/src/main/resources/application-prod.yml
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/AuthServiceImplTest.java
Labels: enhancement

#115 [feat] 레시피 검색할 때 찜한 레시피 제외하고 리스트 반환
  jamanchu/src/main/java/com/recipe/jamanchu/controller/RecipeController.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/RecipeRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/ScrapedRecipeRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/RecipeService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeServiceImplTest.java
Labels: enhancement

#118 [fix] JwtFilter Response CORS 헤더 추가
  jamanchu/src/main/java/com/recipe/jamanchu/auth/jwt/JwtFilter.java
  jamanchu/src/main/java/com/recipe/jamanchu/config/WebMvcConfig.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ConstantsType.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: fix

#123 [feat] AWS S3 도입
  jamanchu/build.gradle
  jamanchu/src/main/java/com/recipe/jamanchu/config/S3Config.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/ManualEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/RecipeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/PictureType.java
  jamanchu/src/main/java/com/recipe/jamanchu/util/PictureManager.java
  jamanchu/src/main/resources/application-dev.yml
  jamanchu/src/main/resources/application-prod.yml
Labels: enhancement

#125 [feat] 회원 탈퇴 기능 수정 및 회원 정보 삭제 기능 구현
  jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/UserController.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/BaseTimeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/RecipeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/UserEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/auth/DeleteUserDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/CommentRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/IngredientRatingRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/RecipeRatingRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/RecipeRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/ScrapedRecipeRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/UserRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/UserService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/component/UserAccessHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: enhancement

#127 [fix] 조건 검색 오류 수정
  jamanchu/src/main/java/com/recipe/jamanchu/controller/RecipeController.java
Labels: fix

#131 [feat] 레시피 등록 / 수정 시 S3 연동
  jamanchu/src/main/java/com/recipe/jamanchu/controller/PictureController.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/RecipeController.java
  jamanchu/src/main/java/com/recipe/jamanchu/entity/RecipeEntity.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/request/recipe/RecipesUpdateDTO.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/PictureService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/RecipeService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/PictureServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/RecipeServiceImplTest.java
Labels: enhancement

#128 [feat] 회원 가입 전 이메일 검증 API 수정
  jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/ExceptionStatus.java
  jamanchu/src/main/java/com/recipe/jamanchu/exceptions/exception/WithdrewUserException.java
  jamanchu/src/test/java/com/recipe/jamanchu/component/UserAccessHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: enhancement

#132 [feat] 일반 로그인 카카오 로그인 로직 수정
  jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/UserRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/component/UserAccessHandlerTest.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/UserServiceImplTest.java
Labels: enhancement

#130 [feat] 1차 추천 알고리즘 로직 구현
  jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
  jamanchu/src/main/java/com/recipe/jamanchu/controller/RecipeController.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/recipes/RecommendRecipe.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/dto/response/recipes/RecommendRecipes.java
  jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/CommentRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/repository/RecipeRatingRepository.java
  jamanchu/src/main/java/com/recipe/jamanchu/schedule/RecommendScheduler.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/RecipeService.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/CommentsServiceImpl.java
  jamanchu/src/main/java/com/recipe/jamanchu/service/impl/RecipeServiceImpl.java
  jamanchu/src/test/java/com/recipe/jamanchu/service/impl/CommentsServiceImplTest.java
Labels: enhancement

#137 [feat] 조건 검색 재료명 부분 검색 되도록 수정
  jamanchu/build.gradle
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/QuerydslConfig.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImplTest.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/RecipeRepository.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/RecipeRepositoryCustom.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/impl/RecipeRepositoryCustomImpl.java
Labels: enhancement

#138 [feat] docker settings
  docker-compose.yml
  jamanchu/Dockerfile_API
  jamanchu/Dockerfile_Batch
Labels: enhancement

#141 [fix] multi module package 변경
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/auth/oauth2/CustomOauth2UserService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/auth/service/CustomUserDetailService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/schedule/RecommendScheduler.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/UserServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/component/UserAccessHandlerTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/UserServiceImplTest.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/recommend/schedule/RecommendScheduler.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/component/UserAccessHandler.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/auth/KakaoUserDetails.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/auth/UserDetailsDTO.java
Labels: fix

#142 [HOTFIX] RecipeServiceImpl import 수정
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImpl.java
Labels: fix

#144 [fix] UserAccessHandler 의존성 문제 해결
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/RecipeService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/AuthServiceImpl.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/CommentsServiceImpl.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/NotifyServiceImpl.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeDivideServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/auth/service/CustomUserDetailServiceTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/AuthServiceImplTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/CommentsServiceImplTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/NotifyServiceImplTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/RecipeDivideServiceImplTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImplTest.java
  jamanchu/module-batch/build.gradle
  jamanchu/module-batch/src/main/resources/application-dev.yml
  jamanchu/module-batch/src/main/resources/application-prod.yml
Labels: fix

#146 [feat] 추천 로직 패키지 변경 및 Test Code
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImpl.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/BatchApplication.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/recommend/RecommendCalculate.java
  jamanchu/module-batch/src/test/java/com/recipe/jamanchu/batch/recommend/RecommendCalculateTest.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/entity/RecommendRecipeEntity.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/RecommendRecipeRepository.java
Labels: enhancement

#148 [HOTFIX] Rating이 1.0이상인 평가들만 조회 메서드 추가
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImpl.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/RecipeRatingRepository.java
Labels: fix

#150 [feat] Comment Spring Security 경로 추가
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/SecurityConfig.java
Labels: enhancement

#151 [feat] Seasoning entity 추가
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeDivideServiceImpl.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImplTest.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/entity/SeasoningEntity.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/SeasoningRepository.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/util/SeasoningDataInitializer.java
Labels: enhancement

#155 [feat] 레시피 조회 시에 전체 레시피 갯수도 반환하도록 추가
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImpl.java
Labels: enhancement

#157 [fix] 모듈화로 인한 의존성 문제 해결
  jamanchu/build.gradle
  jamanchu/module-api/build.gradle
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/PictureServiceImpl.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/util/PictureManager.java
  jamanchu/module-core/src/main/java/com/recipe/jamanchu/core/config/BCryptEncoderConfig.java
  jamanchu/module-core/src/main/java/com/recipe/jamanchu/core/config/JpaConfig.java
  jamanchu/module-core/src/main/java/com/recipe/jamanchu/core/config/QuerydslConfig.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/type/PictureType.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/UserRepository.java
Labels: fix

#159 [feat] 특정 알림에 대한 알림 기능 구현 및 테스트 코드
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/notify/IgnoreRecipeCommentAlarmMap.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/notify/NotifyComponent.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/notify/NotifyController.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/notify/SseEmitterMap.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/notify/Subscribers.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/NotifyService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/CommentsServiceImpl.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/NotifyServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/CommentsServiceImplTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/NotifyServiceImplTest.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/type/ResultCode.java
Labels: enhancement

#161 [fix] 알림 기능 수정 및 Controller URI 명시적으로 수정
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/notify/IgnoreRecipeCommentAlarmMap.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/notify/NotifyController.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/NotifyServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/NotifyServiceImplTest.java
Labels: fix

#162 [feat] 비밀번호 찾기 api 구현
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/SecurityConfig.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/controller/AuthController.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/AuthService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/AuthServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/component/UserAccessHandlerTest.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/component/UserAccessHandler.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/entity/UserEntity.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/dto/request/auth/PasswordUpdateDTO.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/type/ResultCode.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/UserRepository.java
Labels: enhancement

#165 [fix] Notify Connection Pool이 마르는 문제 해결
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/AsyncConfig.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/SecurityConfig.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/NotifyService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/NotifyServiceImpl.java
Labels: bug

#167 [feat] Recommend 로직 개선
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/recommend/RecommendCalculate.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/recommend/schedule/RecommendComponent.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/recommend/schedule/RecommendRecipeCountsMap.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/recommend/schedule/RecommendRecipeDifferencesMap.java
  jamanchu/module-batch/src/test/java/com/recipe/jamanchu/batch/recommend/RecommendCalculateTest.java
Labels: enhancement

#169 [fix] AuthServiceImplTest 테스트 코드 수정
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/AuthServiceImplTest.java
Labels: fix

#171 [fix] Notify 관련 Authorization 설정 및 Async 제거
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/SecurityConfig.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/NotifyService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/NotifyServiceImpl.java
Labels: fix

#173 [fix] 로그인을 하지않아 알림을 받을 수 없는 유저에게 알림을 전송하는 경우 처리
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/NotifyServiceImpl.java
Labels: fix

#177 [feat] notify recipe Id element 추가
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/CommentsServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/NotifyServiceImplTest.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/dto/response/notify/Notify.java
Labels: fix

#179 [feat] comment 작성 시 레시피, 재료 평가 데이터 저장
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/CommentsServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/CommentsServiceImplTest.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/type/ResultCode.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/CommentRepository.java
Labels: enhancement

#181 [feat] Recommend Recipe 내부 필드에 평점, 조리시간, 조리 난이도 속성 추가
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImplTest.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/dto/response/recipes/RecommendRecipe.java
Labels: enhancement

#183 [refactor] SecurityConfig, JwtFilter 클래스 수정
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/auth/jwt/JwtFilter.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/SecurityConfig.java
Labels: refactor

#185 [feat] statistics api
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/SecurityConfig.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/controller/StatisticsController.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/filter/VisitorCountFilter.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/StatisticsService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/StatisticsServiceImpl.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/component/StatisticsComponent.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/component/bean/StatisticsSet.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/entity/StatisticsEntity.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/type/ResultCode.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/StatisticsRepository.java
Labels: enhancement

#188 [fix] Spring Security 경로 추가
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/auth/jwt/JwtFilter.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/SecurityConfig.java
Labels: fix

#193 [feat] statistics 로직 변경
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/StatisticsServiceImpl.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/entity/StatisticsEntity.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/StatisticsRepository.java
Labels: enhancement

#195 [fix] Comment 저장 시 재료에 대한 point 계산 후 삽입
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/CommentsServiceImpl.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/IngredientRatingRepository.java
Labels: fix

#204 [fix] RageRequest Sort.by id에서 rcpId로 변경
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImpl.java
Labels: fix

#200 [feat] Redis Caching 적용
  docker-compose.yml
  jamanchu/module-api/build.gradle
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/RedisConfig.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeServiceImpl.java
  jamanchu/module-api/src/main/resources/application-dev.yml
  jamanchu/module-api/src/main/resources/application-prod.yml
Labels: enhancement

#203 [feat] monitoring Docker compose
  .gitignore
  data/grafana/env.grafana
  data/prometheus/config/prometheus.yml
  data/prometheus/config/rule.yml
  docker-compose.yml
  jamanchu/module-api/build.gradle
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/auth/jwt/JwtFilter.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/config/SecurityConfig.java
  jamanchu/module-api/src/main/resources/application-dev.yml
  jamanchu/module-api/src/main/resources/application-prod.yml
  jamanchu/module-core/build.gradle
Labels: enhancement

#205 [refactor] 불필요한 클래스 삭제 및 크롤링 데이터 chunk 단위로 처리
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/controller/DataSaveController.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/controller/ScrapTenThousandRecipeController.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/scraper/ScrapTenThousandRecipe.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/ScrapTenThousandRecipeService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/RecipeDivideServiceImpl.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/ScrapTenThousandRecipeServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/scraper/ScrapTenThousandRecipeTest.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/component/recipe/RecipeDivide.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/component/recipe/ScrapTenThousandRecipe.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/component/recommend/RecommendCalculate.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/component/recommend/schedule/RecommendComponent.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/component/recommend/schedule/RecommendRecipeCountsMap.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/component/recommend/schedule/RecommendRecipeDifferencesMap.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/job/CrawlDataJob.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/job/RecommendCalculateJob.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/recipe/RecipeDivide.java
  jamanchu/module-batch/src/main/java/com/recipe/jamanchu/batch/step/crawlDataStep/ScrapDataStep.java
  jamanchu/module-batch/src/test/java/com/recipe/jamanchu/batch/recommend/RecommendCalculateTest.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/component/UserAccessHandler.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/entity/TenThousandRecipeEntity.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/repository/UserRepository.java
Labels: refactor

#207 [refactor] batch 모듈 prod.yml 파일 수정 및 TenThousandRecipeEntity 어노테이션 추가
  jamanchu/module-batch/src/main/resources/application-prod.yml
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/entity/TenThousandRecipeEntity.java
Labels: refactor

#211 [fix] refresh 토큰 헤더명 변경 및 재발급 로직 수정
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/controller/AuthController.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/AuthService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/AuthServiceImpl.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/UserServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/component/UserAccessHandlerTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/AuthServiceImplTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/RecipeDivideServiceImplTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/ScrapTenThousandRecipeServiceImplTest.java
  jamanchu/module-domain/src/main/java/com/recipe/jamanchu/domain/model/type/TokenType.java
Labels: fix

#213 [fix] nickname 값에서 userId 값으로 변경
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/controller/AuthController.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/AuthService.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/AuthServiceImpl.java
  jamanchu/module-api/src/main/java/com/recipe/jamanchu/api/service/impl/UserServiceImpl.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/AuthServiceImplTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/RecipeDivideServiceImplTest.java
  jamanchu/module-api/src/test/java/com/recipe/jamanchu/api/service/impl/ScrapTenThousandRecipeServiceImplTest.java
Labels: fix
